// Generated by CoffeeScript 1.6.3
(function() {
  define(['R'], function(R) {
    return {
      init: function() {
        return $(document).ready(function() {
          var descriptionEnabled;
          $('dd').css('display', 'none');
          descriptionEnabled = false;
          $(".btn-info").click(function() {
            if (descriptionEnabled) {
              $('dd').css('display', 'none');
              $('.container').css('width', '');
              return descriptionEnabled = false;
            } else {
              $('dd').css('display', 'inline');
              $('.container').css('width', '700px');
              return descriptionEnabled = true;
            }
          });
          return $(".btn-more-urls").click(function() {
            return chrome.tabs.getSelected(null, function(tab) {
              return chrome.tabs.update(tab.id, {
                url: "chrome://about/"
              });
            });
          });
        });
      }
    };
  });

}).call(this);
