// Generated by CoffeeScript 1.6.3
(function() {
  define(['R', '_'], function(R, _) {
    return {
      init: function() {
        return $(document).ready(function() {
          var descriptionEnabled;
          $('dd').css('display', 'none');
          descriptionEnabled = false;
          $(".btn-info").click(function() {
            if (descriptionEnabled) {
              $('dd').css('display', 'none');
              $('.container').css('width', '');
              return descriptionEnabled = false;
            } else {
              $('dd').css('display', 'inline');
              $('.container').css('width', '700px');
              return descriptionEnabled = true;
            }
          });
          $('.btn-more-urls').click(function() {
            return chrome.tabs.create({
              'url': "chrome://about/"
            });
          });
          return $('dt').click(function() {
            return _.redirectTo($(this).text());
          });
        });
      }
    };
  });

}).call(this);
