// Generated by CoffeeScript 1.6.3
(function() {
  var __slice = [].slice;

  require.config({
    paths: {
      R: 'core/data/Resources',
      app: 'view/app',
      _: 'core/common/Utils'
    }
  });

  require(['_', 'app'], function() {
    var c, components, _i, _len, _results;
    components = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    _results = [];
    for (_i = 0, _len = components.length; _i < _len; _i++) {
      c = components[_i];
      _results.push(typeof c.init === "function" ? c.init() : void 0);
    }
    return _results;
  });

}).call(this);
