// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    return {
      redirectTo: function(url) {
        return chrome.tabs.getSelected(null, function(tab) {
          return chrome.tabs.update(tab.id, {
            url: url
          });
        });
      },
      copyToClipboard: function(text) {
        var copyDiv;
        copyDiv = document.createElement("div");
        copyDiv.contentEditable = true;
        document.body.appendChild(copyDiv);
        copyDiv.innerHTML = text;
        copyDiv.unselectable = "off";
        copyDiv.focus();
        document.execCommand("SelectAll");
        document.execCommand("RemoveFormat");
        document.execCommand("Copy", false, null);
        return document.body.removeChild(copyDiv);
      },
      selectText: function(element) {
        var doc, range, selection, text;
        doc = document;
        text = doc.getElementById(element);
        if (doc.body.createTextRange) {
          range = doc.body.createTextRange();
          range.moveToElementText(text);
          return range.select();
        } else if (window.getSelection) {
          selection = window.getSelection();
          range = doc.createRange();
          range.selectNodeContents(text);
          selection.removeAllRanges();
          return selection.addRange(range);
        }
      }
    };
  });

}).call(this);
