// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    return {
      redirectTo: function(url) {
        return chrome.tabs.getSelected(null, function(tab) {
          return chrome.tabs.update(tab.id, {
            url: url
          });
        });
      }
    };
  });

}).call(this);
